#!/usr/bin/env sh

# Expected to be run as a separate user, in the repo to be used for building
# repo can be empty
# Offline root is expected to be passed via env SPICE_OFFLINE, e.g.:
# SPICE_OFFLINE=/Volumes/data/offline && curl https://tools.svnx.dev/setup/spice/agent | sh -

echo "Preparing repo"

mkdir -p $HOME/Library/Caches/spice
echo "export SPICE_REPO=$(pwd)" > $HOME/Library/Caches/spice/env.sh

echo "Installing agent"
brew tap 44/tap
brew update
brew install spice-agent

echo "Configuring Xcode"

defaults write com.apple.dt.xcodebuild PBXNumberOfParallelBuildSubtasks 4
defaults write com.apple.dt.xcodebuild IDEBuildOperationMaxNumberOfConcurrentCompileTasks 4
defaults write com.apple.dt.Xcode PBXNumberOfParallelBuildSubtasks 4
defaults write com.apple.dt.Xcode IDEBuildOperationMaxNumberOfConcurrentCompileTasks 4

echo "Configuring offline mode"

export SYSTEM_ACCESSTOKEN=irrelevant
nuget sources add -Name "offline" -Source "/Volumes/data/offline/nuget" -ConfigFile $HOME/.CxCache/NugetCache/nuget_server.config
nuget sources disable -Name "OneDrive.Client-Aggregate" -ConfigFile $HOME/.CxCache/NugetCache/nuget_server.config

if [[ -f "$(brew --prefix nvm)/nvm.sh" ]]; then
    echo "Activating node@18 using nvm"
    source $(brew --prefix nvm)/nvm.sh
    nvm use 18
fi

yarn config set yarn-offline-mirror "/Volumes/data/offline/yarn"
yarn config set offline true

